enum ErrorStatus {
	DIRECTORY_EMPTY,
	DIRECTORY_NOT_ABSOLUTE,
	DIRECTORY_NOT_FOUND,
	INVALID_DIRECTORY,
	INVALID_FILE_PATH,
	FILE_CREATION_FAILED,
	FILES_NOT_FOUND,
	INVALID_INDEX,
	INVALID_PATHFILE,
	INVALID_DIRECTORY_FILE_OUTPUT,
	CROMPRESSION_FAILED,
}

export type ErrorStatusType = keyof typeof ErrorStatus;
