export enum ErrorStatus {
	DIRECTORY_EMPTY = 'DIRECTORY_EMPTY',
	DIRECTORY_NOT_ABSOLUTE = 'DIRECTORY_NOT_ABSOLUTE',
	DIRECTORY_NOT_FOUND = 'DIRECTORY_NOT_FOUND',
	INVALID_DIRECTORY = 'INVALID_DIRECTORY',
	INVALID_FILE_PATH = 'INVALID_FILE_PATH',
	FILE_CREATION_FAILED = 'FILE_CREATION_FAILED',
	INVALID_INDEX = 'INVALID_INDEX',
	INVALID_PATHFILE = 'INVALID_PATHFILE',
}
